# Redes hidraulicas

In [15]:
import numpy as np

nv = 5
nc = 7

conec = np.array([ [1,2],[2,3],[3,4],[4,5],[5,2],[5,3],[5,1] ], dtype = int)
conec = conec - 1 #index comeca do zero
print(conec)

C = np.array([2, 2, 1, 2, 1, 2, 2], dtype = float)
print(C)

[[0 1]
 [1 2]
 [2 3]
 [3 4]
 [4 1]
 [4 2]
 [4 0]]
[2. 2. 1. 2. 1. 2. 2.]


1
1
1


In [16]:
def Assembly(nv, nc, C, conec):
    #matriz  dos numeros de canos pelo numero de canos
    A = np.zeros(shape = (nv, nv))
    #percorre os nós
    for k in range (nc):
        #localizacao condutancia
        Cloc = np.array( [ [ C[k], -C[k] ], [ -C[k], C[k] ] ])
        print(Cloc)
        
        p = conec[k, 0]
        q = conec[k, 1]
        A[p,p] += Cloc[0,0]
        A[q,q] += Cloc[1,1]
        A[p,q] += Cloc[0,1]
        A[q,p] += Cloc[1,0]
    return A

A = Assembly(nv, nc, C, conec)
print(A)

[[ 2. -2.]
 [-2.  2.]]
[[ 2. -2.]
 [-2.  2.]]
[[ 1. -1.]
 [-1.  1.]]
[[ 2. -2.]
 [-2.  2.]]
[[ 1. -1.]
 [-1.  1.]]
[[ 2. -2.]
 [-2.  2.]]
[[ 2. -2.]
 [-2.  2.]]
[[ 4. -2.  0.  0. -2.]
 [-2.  5. -2.  0. -1.]
 [ 0. -2.  5. -1. -2.]
 [ 0.  0. -1.  3. -2.]
 [-2. -1. -2. -2.  7.]]


In [19]:
def ResolveRede(nv, nc, C, conec, natm, nb, Qb):
    A = Assembly(nv, nc, C, conec)
    Atilde = np.copy(A)
    
    sum_q=np.zeros(nv, dtype = float)
    sum_q[nb] = Qb
    
    Atilde[natm,:] = 0.0
    Atilde[natm,natm] = 1.0
    
    return np.linealg.solve(Atilde, sum_q)

conec = np.loadtxt('conec')
    
natm = 3-1
nb = 1-1
Qb = 3.0

pressure = ResolveRede(nv, nc, C, conec, natm, nb, Qb)

print(pressure)

FileNotFoundError: conec not found.